version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: find-it-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-Find-It}
      POSTGRES_USER: ${POSTGRES_USER:-keno68}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - find_it_db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: find-it-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  find_it_db_data:
